### ISSUE TITLE
Demo code for basic usage throws a NullPointerException

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CameraKitCodenameOne#8]
After fixing the `build.xml` adding the line mentioned in https://github.com/codenameone/CameraKitCodenameOne/issues/3, I tried the demo code for basic usage reported in https://github.com/codenameone/CameraKitCodenameOne/blob/master/README.md, but it throws the same `NullPointerException` both on Simulator and on Android (I didn't test iOS):

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.RuntimeException: java.lang.NullPointerException
	at com.codename1.camerakit.impl.CameraNativeAccessImpl.getView(Unknown Source)
	at com.codename1.camerakit.CameraKit.getView(CameraKit.java:58)
	at net.informaticalibera.camerakittest.MyApplication.start(MyApplication.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$3$1.run(Executor.java:261)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1303)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1097)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
Caused by: java.lang.NullPointerException
	at com.codename1.camerakit.impl.CameraNativeAccessImpl.getWebcam(Unknown Source)
	at com.codename1.camerakit.impl.CameraNativeAccessImpl.getViewInternal(Unknown Source)
	... 12 more
Java Result: 1
```

**Comment by jsfan3** [comment]
The line `MyApplication.java:82` of the above log is:
`hi.add(ck.getView());`
