### ISSUE TITLE
Full demo project also throws a NullPointerException

### ISSUE THREAD

**Issue by jsfan3** [codenameone/CameraKitCodenameOne#9]
The `NullPointerException` thrown by the demo basic code of the ReadMe (https://github.com/codenameone/CameraKitCodenameOne/issues/8), is thrown also by the demo project https://github.com/codenameone/CameraKitCodenameOne/tree/master/CameraKitDemo:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.NullPointerException
	at com.codename1.camerakit.impl.CameraNativeAccessImpl.getWebcam(Unknown Source)
	at com.codename1.camerakit.impl.CameraNativeAccessImpl.start(Unknown Source)
	at com.codename1.camerakit.CameraKit.start(CameraKit.java:72)
	at com.codename1.camerakit.demo.CameraKitDemo.start(CameraKitDemo.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$3$1.run(Executor.java:261)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1303)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:1097)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
/home/francesco/NetBeansProjects/CameraKitCodenameOne-master/CameraKitDemo/nbproject/build-impl.xml:1328: The following error occurred while executing this line:
/home/francesco/NetBeansProjects/CameraKitCodenameOne-master/CameraKitDemo/nbproject/build-impl.xml:980: Java returned: 1
```

**Comment by shannah** [comment]
I have guarded against the NPE, but it doesn't explain why the lib can't find your system's camera.  If you can figure out how to get the webcam lib we use on simulator working on your environment, then we can probably apply the changes in our cn1lib so that it works on your system.  The library we use is
https://github.com/sarxos/webcam-capture
